#FROM node:16.15.1
#
#WORKDIR /app
#COPY package.json ./
#RUN npm install
#COPY . .
#RUN npm run build
#EXPOSE 3000
#CMD ["npm", "start"]

#docker run -i -t  -p 3000:3000 kristen45/react
FROM node:18-alpine
WORKDIR /react-docker-example/
COPY public/ /react-docker-example/public
COPY src/ /react-docker-example/src
COPY package.json /react-docker-example/
RUN npm install
EXPOSE 3000
CMD ["npm", "start"]
