version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    #mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - microservices-app-network

  config-server:
    image: kristen45/config-server:latest
    #mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - microservices-app-network
    depends_on:
      - zipkin
    environment:
      #default
      SPRING_PROFILES_ACTIVE: native
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  service-registry:
    image: kristen45/service-registry:latest
    #mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - microservices-app-network
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CONFIG_IMPORT: optional:config-server:http://config-server:8888/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  department-service:
    image: kristen45/department-service:latest
    #mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - microservices-app-network
    depends_on:
      - config-server
      - service-registry
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:config-server:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  employee-service:
    image: kristen45/employee-service:latest
    #mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - microservices-app-network
    depends_on:
      - config-server
      - service-registry
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:config-server:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  organization-service:
    image: kristen45/organization-service:latest
    #mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - microservices-app-network
    depends_on:
      - config-server
      - service-registry
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:config-server:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  api-gateway:
    image: kristen45/api-gateway:latest
    #mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - microservices-app-network
    depends_on:
      - config-server
      - service-registry
      - organization-service
      - employee-service
      - department-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:config-server:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
  microservices-app-network: