apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary-deployment
  labels:
    app: salary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salary
  template:
    metadata:
      labels:
        app: salary
    spec:
      containers:
        - name: salary
          image: kristen45/salary-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: salary-service
spec:
  selector:
    app: salary
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085